## Run specific settings

## MinKNOW fast5 dir (searching *recursively* for all fast5 files!)
## specify path to MinKnow output dir (e.g. 20220412_1232_MN37911_FAR54812_bfd8a256 of format: run_date run_time position flow_cell_id run_id_shorthash)


## run012_20231107_FGF14
run:
  experiment_id: run012_20231107_FGF14
  input_dir: example/run012_20231107_FGF14
  sample_sheet: sample_sheets/run012_20231107_FGF14.csv
  barcode_kits:
    - EXP-NBD196
  ## Make your choice (guppy is configured with: flowcell+kit OR cfg). cfg will overrule flowcell+kit in this workflow!
  # flowcell: FLO-MIN106 # starts with "FLO"
  # library_prep_kit: SQK-LSK109 # starts with "SQK" or "VSK"


## Output dir
## outdir: results # default: 'results' # default


## workflow settings ###################################################################################################

## Guppy
guppy_cfg:
  - dna_r9.4.1_450bps_fast.cfg
  # - dna_r9.4.1_450bps_hac.cfg
  # - dna_r9.4.1_450bps_sup.cfg


guppy_basecaller:
  ont-guppy_6.4.6:
    bin: ../opt/ont-guppy_6.4.6/bin/guppy_basecaller # guppy binary
    parameter: --disable_pings --recursive --compress_fastq --do_read_splitting --calib_detect --records_per_fastq 0 --enable_trim_barcodes


nanoplot: --huge --N50 --info_in_report --loglength # --barcoded --plots dot --legacy hex --tsv_stats

